from .user import UserViewSet
from .rol import RolViewSet
from .project_types import ProjectTypesViewSet
from .project import ProjectViewSet
from .city import CityViewSet
from .department import DepartmentViewSet
from .beneficiary import BeneficiaryViewSet
from .sponsor import SponsorViewSet
from .usuario import UsuarioViewSet
from .sector import SectorViewSet