# Generated by Django 4.0.6 on 2022-07-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Activo'), (2, 'Por activar'), (3, 'Inactivo')], default=3),
        ),
    ]
