# Generated by Django 4.0.6 on 2022-08-10 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_city_createdby_remove_city_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tipo', models.IntegerField(choices=[(10, 'Servicio Agua'), (20, 'Servicio Cementerio')])),
                ('no_predio', models.IntegerField(blank=True, null=True)),
                ('anio', models.SmallIntegerField()),
                ('mes', models.SmallIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.usuario')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
