# Generated by Django 4.0.6 on 2022-07-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_project'),
        ('api', '0007_projecttypes'),
    ]

    operations = [
    ]
