# Generated by Django 4.0.6 on 2022-08-11 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.proyecto'),
            preserve_default=False,
        ),
    ]
