# Generated by Django 4.0.6 on 2022-08-13 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_rol_delete_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='no_predio',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='sector',
        ),
        migrations.AddField(
            model_name='servicio',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='api.sector'),
            preserve_default=False,
        ),
    ]
