# Generated by Django 4.0.6 on 2022-08-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='cellphone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
