# Generated by Django 4.0.6 on 2022-08-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_beneficiary_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Otro')], null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
