# Generated by Django 4.0.6 on 2022-08-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_loads_cities_deparments'),
        ('api', '0012_sponsor'),
    ]

    operations = [
    ]
