# Generated by Django 4.0.6 on 2022-08-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_tipo_detalle_tipo_movimiento_detalle_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
