# Generated by Django 4.0.6 on 2022-09-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_has_temp_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
    ]
