# Generated by Django 4.0.6 on 2022-08-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sector_usuario_remove_parentrel_beneficiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.sector'),
        ),
    ]
